"""Tools for studying identifiability of scaling-law extrapolation."""

from .baselines import (
    ParametricFit,
    fit_floor_power,
    fit_two_power,
    laplace_floor_power_interval,
    parametric_bootstrap_interval,
)
from .certificate import (
    CertificateInterval,
    certificate_curve,
    certificate_interval,
    certificate_interval_from_bands,
    continuous_cell_matrices,
    continuous_certificate_curve,
    continuous_certificate_interval,
    continuous_certificate_interval_from_bands,
    design_matrix,
    gaussian_observation_bands,
    minimum_uniform_band_radius,
    simultaneous_gaussian_multiplier,
)
from .finite_sample import (
    TrainedCurveSummary,
    direct_ols_population_risk_draws,
    expected_ols_population_risk,
    ols_debias_multiplier,
    ols_mean_multiplier,
    sample_ols_population_risk,
    simulate_ols_curve,
)
from .spectral import (
    BasisName,
    MatchedPair,
    asymptotic_tail,
    evaluate_basis,
    exponent_curvature_upper,
    hidden_weight_for_tolerance,
    mixture_risk,
    power_basis,
    power_exponent_curvature,
    tail_basis,
    tail_exponent_curvature_upper,
)

__all__ = [
    "BasisName",
    "CertificateInterval",
    "MatchedPair",
    "ParametricFit",
    "TrainedCurveSummary",
    "asymptotic_tail",
    "certificate_curve",
    "certificate_interval",
    "certificate_interval_from_bands",
    "continuous_cell_matrices",
    "continuous_certificate_curve",
    "continuous_certificate_interval",
    "continuous_certificate_interval_from_bands",
    "design_matrix",
    "direct_ols_population_risk_draws",
    "evaluate_basis",
    "expected_ols_population_risk",
    "exponent_curvature_upper",
    "fit_floor_power",
    "fit_two_power",
    "gaussian_observation_bands",
    "hidden_weight_for_tolerance",
    "laplace_floor_power_interval",
    "minimum_uniform_band_radius",
    "mixture_risk",
    "ols_debias_multiplier",
    "ols_mean_multiplier",
    "parametric_bootstrap_interval",
    "power_basis",
    "power_exponent_curvature",
    "sample_ols_population_risk",
    "simultaneous_gaussian_multiplier",
    "simulate_ols_curve",
    "tail_basis",
    "tail_exponent_curvature_upper",
]
